import type { Metadata } from "next";
import localFont from "next/font/local";
import { Header } from "../Header";
import { Footer } from "../Footer";

const defaultFont = localFont({
  src: [
    {
      path: "../fonts/Satoshi/Satoshi-Light.ttf",
      weight: "300",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Test App",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <div style={{ fontFamily: defaultFont.style.fontFamily }}>
      <header>
        <Header />
      </header>
      <main>{children}</main>
      <footer>
        <Footer />
      </footer>
    </div>
  );
}
