import type { Metadata } from "next";
import localFont from "next/font/local";
import { Header } from "./Header";
import { Footer } from "./Footer";

const defaultFont = localFont({
  src: [
    {
      path: "./fonts/Satoshi/Satoshi-Light.ttf",
      weight: "300",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Test App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      style={{
        fontFamily: defaultFont.style.fontFamily,
        backgroundColor: "#b1b4ef",
      }}
    >
      <head>
        <link
          href="https://api.fontshare.com/v2/css?f[]=satoshi@301&display=swap"
          rel="stylesheet"
        />
      </head>
      <body style={{ margin: 0 }}>
        <header>
          <Header />
        </header>
        {children}
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
